name: "Cache Checker (PR)"
on:
  push:
    branches:
      - dev

jobs:
  check_warnings:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up ASDF
        uses: asdf-vm/actions/setup@v2.2.0
      - name: Cache ASDF
        id: cache
        uses: actions/cache@v3
        with:
          path: ~/.asdf
          key: asdf-${{ hashFiles('.tool-versions') }}
      - name: Install NodeJS
        if: steps.cache.outputs.cache-hit != 'true'
        uses: asdf-vm/actions/install@v2
      - name: Run
        run: node src/index.js
